import {readdirSync, readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

console.log(`Rename results for comment action`);

const path = './examples/github-report/measures';

const reportPath = readdirSync(path).find((p) => p.endsWith('.md'));

if (!reportPath) {
  throw new Error('Report file not found');
}

const targetPath = join(path, reportPath);
const destPath = join(path, 'md-report.md');

let report = readFileSync(targetPath, {encoding: 'utf8'});

report = `
❗❗❗ **report generated by this PR** ❗❗❗
---

` + report;

writeFileSync(destPath, report);
console.log(`Report ${targetPath} renamed to ${destPath}`);
