name: user-flow-md-report-test

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: build
        run: npm run build-all
      - name: run
        run: npm run md-report-test
      - name: Add reduced report as comment to the PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          header: md-report-test
          path: ./dist/user-flow/user-flow-gh-integration/md-report.md
