name: user-flow-gh-action-demo
on:
  pull_request:
jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: run:user-flow
        uses: push-based/user-flow-gh-action@v0.1.0
        with:
          rcPath: packages/user-flow-ci-integration/.user-flowrc.json
