name: user-flow-gh-action-demo
on:
  pull_request:
jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: run:user-flow-action
        uses: push-based/user-flow-gh-action@v0.3.2
        with:
          rcPath: packages/user-flow-gh-integration/.user-flowrc.json
