name: user-flow

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm i
      - name: build
        run: npm run build
      - name: Executing user-flow CLI
        run: npx @push-based/user-flow collect --rcPath ./packages/user-flow-ci-integration/.user-flowrc.json
        #uses: push-based/user-flow-gh-action@v0.0.0-alpha.4
        #with:
        #  verbose: on
        #  rcPath: ./packages/user-flow-ci-integration/.user-flowrc.json
      - name: Commit measures
        uses: EndBug/add-and-commit@v2
        with:
          author_name: push-based-bot
          author_email: opensource@push-based.io
          message: 'Persist user flow reports'
          add: '*'
      - name: Add reduced report as comment to the PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: step name
          path: ./packages/user-flow-ci-integration/measures/order-coffee-in-ci.uf.json
