name: user-flow

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm i
      - name: build
        run: npm run build
      - name: Add reduced report as comment to the PR
        uses: @push-based/user-flow-gh-action
        with:
          rcPath: ./user-flow.rc
      - name: Add reduced report as comment to the PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: step name
          path: ./packages/user-flow-ci-integration/measures/order-coffee-in-ci.uf.md
