name: user-flow

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm i
      - name: build
        run: npm run nx -- build cli
      - name: user-flow ci test
        run: npm run ci-test
      - name: Create report comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body-file: './packages/user-flow-ci-integration/measures/order-coffee.uf.md'
