name: user-flow

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm i
      - name: build
        run: npm run build
      - name: user-flow ci test
        run: npm run ci-test
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create report comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.pr.outputs.pull_request_number }}
          body-file: './packages/user-flow-ci-integration/measures/order-coffee-in-ci.uf.md'
