name: user-flow-gh-integration

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        node-version: [22.x]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: install
        run: npm ci

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: run:user-flow-action
        uses: push-based/user-flow-gh-action@v0.3.2
        with:
          rcPath: examples/github-report/.user-flowrc.json
